// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfxNYf8EM6BNXXiTJ1vXdkvtsNVZFVQfE',
    appId: '1:864046346586:web:0d2023a6ac26493d2a8363',
    messagingSenderId: '864046346586',
    projectId: 'roundus-game',
    authDomain: 'roundus-game.firebaseapp.com',
    storageBucket: 'roundus-game.firebasestorage.app',
    measurementId: 'G-6JN70NGGBF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDk1v7_NVW6R2g--y4ZCnVw5ayXDHXpjpM',
    appId: '1:864046346586:android:e07720964f50a87f2a8363',
    messagingSenderId: '864046346586',
    projectId: 'roundus-game',
    storageBucket: 'roundus-game.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrvlfAUx1TvpcW_X5h8HflIjAuTcL7kzw',
    appId: '1:864046346586:ios:a69677ad57c76b4c2a8363',
    messagingSenderId: '864046346586',
    projectId: 'roundus-game',
    storageBucket: 'roundus-game.firebasestorage.app',
    iosBundleId: 'com.example.roundusClean',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrvlfAUx1TvpcW_X5h8HflIjAuTcL7kzw',
    appId: '1:864046346586:ios:f03550fb7ee108542a8363',
    messagingSenderId: '864046346586',
    projectId: 'roundus-game',
    storageBucket: 'roundus-game.firebasestorage.app',
    iosBundleId: 'com.example.roundus',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDfxNYf8EM6BNXXiTJ1vXdkvtsNVZFVQfE',
    appId: '1:864046346586:web:3587299b720646bf2a8363',
    messagingSenderId: '864046346586',
    projectId: 'roundus-game',
    authDomain: 'roundus-game.firebaseapp.com',
    storageBucket: 'roundus-game.firebasestorage.app',
    measurementId: 'G-3K5RR5GL3C',
  );

}