// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxUwwOoRUn80R0liZljG8viaFwWNPYZKY',
    appId: '1:954180373576:web:4131b1bc6eb01576be9c7d',
    messagingSenderId: '954180373576',
    projectId: 'roundus-c5f22',
    authDomain: 'roundus-c5f22.firebaseapp.com',
    storageBucket: 'roundus-c5f22.firebasestorage.app',
    measurementId: 'G-CFXSRPG0G6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhkjXFEUjDeykqm1hE_as4QFGn11jOGxc',
    appId: '1:954180373576:android:229ecf1b8d180936be9c7d',
    messagingSenderId: '954180373576',
    projectId: 'roundus-c5f22',
    storageBucket: 'roundus-c5f22.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBS9nPhTJpZQj0dE9xy9EfwFQMiz8v1jY',
    appId: '1:954180373576:ios:a7da5e3464670d5dbe9c7d',
    messagingSenderId: '954180373576',
    projectId: 'roundus-c5f22',
    storageBucket: 'roundus-c5f22.firebasestorage.app',
    androidClientId: '954180373576-cmv1q4t3digg7j0kcs2agf6ho1k63g47.apps.googleusercontent.com',
    iosClientId: '954180373576-6o8aipuhq8vh9rfgs5d4onqe1m42a0gp.apps.googleusercontent.com',
    iosBundleId: 'com.example.rounders',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBS9nPhTJpZQj0dE9xy9EfwFQMiz8v1jY',
    appId: '1:954180373576:ios:a7da5e3464670d5dbe9c7d',
    messagingSenderId: '954180373576',
    projectId: 'roundus-c5f22',
    storageBucket: 'roundus-c5f22.firebasestorage.app',
    androidClientId: '954180373576-cmv1q4t3digg7j0kcs2agf6ho1k63g47.apps.googleusercontent.com',
    iosClientId: '954180373576-6o8aipuhq8vh9rfgs5d4onqe1m42a0gp.apps.googleusercontent.com',
    iosBundleId: 'com.example.rounders',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxUwwOoRUn80R0liZljG8viaFwWNPYZKY',
    appId: '1:954180373576:web:40cf180d8486bff4be9c7d',
    messagingSenderId: '954180373576',
    projectId: 'roundus-c5f22',
    authDomain: 'roundus-c5f22.firebaseapp.com',
    storageBucket: 'roundus-c5f22.firebasestorage.app',
    measurementId: 'G-RWXJ6P4Y66',
  );
}
